port: 8080
connector:
  "source-chatgpt.vanus.svc.cluster.local":
    8ef3e69anxix17e7: 645a1a8ff771bb92f89a1098
  "source-chatai.vanus.svc.cluster.local":
    xxxxxxxxxxxxxxxx: zzzzzzzzzzzzzzzzzzzzzzzz
