apiVersion: v1
kind: Service
metadata:
  name: source-chatai-proxy
  namespace: vanus
spec:
  selector:
    name: source-chatai-proxy
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      name: proxy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: source-chatai-proxy-config
  namespace: vanus
data:
  config.yml: |-
    port: 8080
    connector:
      "source-chatai.vanus.svc.cluster.local":
        8oi60k4sili2pe9y: 6438ab8131c2f1a7b1d6eb63
        hdqjqhowci0wap21: 643cca1331c2f1a7b1d6ebd4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-chatai-proxy
  namespace: vanus
spec:
  replicas: 1
  selector:
    matchLabels:
      name: source-chatai-proxy
  template:
    metadata:
      labels:
        name: source-chatai-proxy
    spec:
      serviceAccountName: vanus-operator
      terminationGracePeriodSeconds: 10
      containers:
      - name: container1
        # Replace this with the built image name
        image: public.ecr.aws/vanus/connector/proxy:chatai
        imagePullPolicy: Always
        volumeMounts:
          - name: config
            mountPath: /vanus/config
      volumes:
        - name: config
          configMap:
            name: source-chatai-proxy-config
