apiVersion: v1
kind: Service
metadata:
  name: myproxy
  namespace: vanus
spec:
  selector:
    name: myproxy
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      name: proxy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myproxy
  namespace: vanus
data:
  config.yml: |-
    port: 8080
    connector:
      "vanus-connect-runtime.vanus.svc.cluster.local":
        8ef3e69anxix17e7: 645a1a8ff771bb92f89a1098
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myproxy
  namespace: vanus
spec:
  replicas: 1
  selector:
    matchLabels:
      name: myproxy
  template:
    metadata:
      labels:
        name: myproxy
    spec:
      serviceAccountName: vanus-operator
      terminationGracePeriodSeconds: 10
      containers:
      - name: container1
        # Replace this with the built image name
        image: public.ecr.aws/vanus/connector/proxy:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: myproxy
            mountPath: /vanus/config
      volumes:
        - name: myproxy
          configMap:
            name: myproxy
